version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  # go:
  #   image: golang:1.22.3
  #   volumes:
  #     - ~/apps/go:/go
  #   working_dir: /go
  #   command: bash -c "while true; do sleep 1000; done"
  #   ports:
  #     - "6969:6969"
